package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: ANSWERS
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Answer"
 *    local-jndi-name="ejb.AnswerLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Answer o"
 *
 * @ejb.persistence table-name="ANSWERS"
 *
 * @weblogic.cache concurrency-strategy="ReadOnly"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class AnswerBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.QuestionnaireLocal.
    *
    *
    * @ejb.relation
    *    name="QUESTIONNAIRES-cmp20-ANSWERS-cmp20"
    *    role-name="ANSWERS-cmp20-has-QUESTIONNAIRES-cmp20"
    *    target-ejb="Questionnaire"
    *    target-role-name="QUESTIONNAIRES-cmp20-has-ANSWERS-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_QUESTIONNAIREID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_QUESTIONNAIREID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.QuestionnaireLocal getQuestionnaire();

   /**
    * Sets the related com.ejdoab.tcms.entities.QuestionnaireLocal
    *
    * @param com.ejdoab.tcms.entities.AnswerLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param questionnaire the new CMR value
    */
   public abstract void setQuestionnaire(com.ejdoab.tcms.entities.QuestionnaireLocal questionnaire);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.UserLocal.
    *
    *
    * @ejb.relation
    *    name="USERS-cmp20-ANSWERS-cmp20"
    *    role-name="ANSWERS-cmp20-has-USERS-cmp20"
    *    target-ejb="User"
    *    target-role-name="USERS-cmp20-has-ANSWERS-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_USERID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_USERID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.UserLocal getUser();

   /**
    * Sets the related com.ejdoab.tcms.entities.UserLocal
    *
    * @param com.ejdoab.tcms.entities.AnswerLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param user the new CMR value
    */
   public abstract void setUser(com.ejdoab.tcms.entities.UserLocal user);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param questionnaire mandatory CMR field
    * @param user mandatory CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( com.ejdoab.tcms.entities.QuestionnaireLocal questionnaire, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "ANSWERS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param questionnaire mandatory CMR field
    * @param user mandatory CMR field
    */
   public void ejbPostCreate( com.ejdoab.tcms.entities.QuestionnaireLocal questionnaire, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Set CMR fields
      setQuestionnaire(questionnaire);
      setUser(user);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-answers-class-code.txt found.

}
