package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: CONFERENCES
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Conference"
 *    local-jndi-name="ejb.ConferenceLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Conference o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByName(java.lang.String name)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.name = ?1"
 *    description="NAME is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByDescription(java.lang.String description)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.description = ?1"
 *    description="DESCRIPTION is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByStartDate(java.util.Date startDate)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.startDate = ?1"
 *    description="STARTDATE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByEndDate(java.util.Date endDate)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.endDate = ?1"
 *    description="ENDDATE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByAbstractSubmissionStartDate(java.util.Date abstractSubmissionStartDate)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.abstractSubmissionStartDate = ?1"
 *    description="ABSTRACTSUBMISSIONSTARTDATE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByAbstractSubmissionEndDate(java.util.Date abstractSubmissionEndDate)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Conference o WHERE o.abstractSubmissionEndDate = ?1"
 *    description="ABSTRACTSUBMISSIONENDDATE is not indexed."
 *
 * @ejb.persistence table-name="CONFERENCES"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class ConferenceBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the name
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the name
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="NAME"
    */
   public abstract java.lang.String getName();

   /**
    * Sets the name
    *
    * @param java.lang.String the new name value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setName(java.lang.String name);

   /**
    * Returns the description
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the description
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="DESCRIPTION"
    */
   public abstract java.lang.String getDescription();

   /**
    * Sets the description
    *
    * @param java.lang.String the new description value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setDescription(java.lang.String description);

   /**
    * Returns the startDate
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the startDate
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="STARTDATE"
    */
   public abstract java.util.Date getStartDate();

   /**
    * Sets the startDate
    *
    * @param java.util.Date the new startDate value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setStartDate(java.util.Date startDate);

   /**
    * Returns the endDate
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the endDate
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="ENDDATE"
    */
   public abstract java.util.Date getEndDate();

   /**
    * Sets the endDate
    *
    * @param java.util.Date the new endDate value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setEndDate(java.util.Date endDate);

   /**
    * Returns the abstractSubmissionStartDate
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the abstractSubmissionStartDate
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="ABSTRACTSUBMISSIONSTARTDATE"
    */
   public abstract java.util.Date getAbstractSubmissionStartDate();

   /**
    * Sets the abstractSubmissionStartDate
    *
    * @param java.util.Date the new abstractSubmissionStartDate value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setAbstractSubmissionStartDate(java.util.Date abstractSubmissionStartDate);

   /**
    * Returns the abstractSubmissionEndDate
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the abstractSubmissionEndDate
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="ABSTRACTSUBMISSIONENDDATE"
    */
   public abstract java.util.Date getAbstractSubmissionEndDate();

   /**
    * Sets the abstractSubmissionEndDate
    *
    * @param java.util.Date the new abstractSubmissionEndDate value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setAbstractSubmissionEndDate(java.util.Date abstractSubmissionEndDate);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.VenueLocal.
    *
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="VENUES-cmp20-CONFERENCES-cmp20"
    *    role-name="CONFERENCES-cmp20-has-VENUES-cmp20"
    *    target-ejb="Venue"
    *    target-role-name="VENUES-cmp20-has-CONFERENCES-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_VENUEID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_VENUEID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.VenueLocal getVenue();

   /**
    * Sets the related com.ejdoab.tcms.entities.VenueLocal
    *
    * @param com.ejdoab.tcms.entities.ConferenceLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param venue the new CMR value
    */
   public abstract void setVenue(com.ejdoab.tcms.entities.VenueLocal venue);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.TrackLocal.
    * middlegen.plugins.entitybean.Entity20Table@bc36ff
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="CONFERENCES-cmp20-TRACKS-cmp20"
    *    role-name="CONFERENCES-cmp20-has-TRACKS-cmp20"
    *    target-ejb="Track"
    *    target-role-name="TRACKS-cmp20-has-CONFERENCES-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_CONFERENCEID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_CONFERENCEID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getTracks();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.TrackLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.TrackLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param tracks the new CMR value
    */
   public abstract void setTracks(java.util.Collection tracks);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "CONFERENCES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param name the name value
    * @param description the description value
    * @param startDate the startDate value
    * @param endDate the endDate value
    * @param abstractSubmissionStartDate the abstractSubmissionStartDate value
    * @param abstractSubmissionEndDate the abstractSubmissionEndDate value
    * @param venue CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String name, java.lang.String description, java.util.Date startDate, java.util.Date endDate, java.util.Date abstractSubmissionStartDate, java.util.Date abstractSubmissionEndDate, com.ejdoab.tcms.entities.VenueLocal venue ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "CONFERENCES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setName(name);
      setDescription(description);
      setStartDate(startDate);
      setEndDate(endDate);
      setAbstractSubmissionStartDate(abstractSubmissionStartDate);
      setAbstractSubmissionEndDate(abstractSubmissionEndDate);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param name the name value
    * @param description the description value
    * @param startDate the startDate value
    * @param endDate the endDate value
    * @param abstractSubmissionStartDate the abstractSubmissionStartDate value
    * @param abstractSubmissionEndDate the abstractSubmissionEndDate value
    * @param venue CMR field
    */
   public void ejbPostCreate( java.lang.String name, java.lang.String description, java.util.Date startDate, java.util.Date endDate, java.util.Date abstractSubmissionStartDate, java.util.Date abstractSubmissionEndDate, com.ejdoab.tcms.entities.VenueLocal venue ) throws javax.ejb.CreateException {
      // Set CMR fields
      setVenue(venue);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-conferences-class-code.txt found.

}
