package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: GROUPPRICINGRULES
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="GroupPricingRule"
 *    local-jndi-name="ejb.GroupPricingRuleLocalHome"
 *    view-type="local"
 *    primkey-field="ruleName"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM GroupPricingRule o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByMinimumAttendees(int minimumAttendees)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM GroupPricingRule o WHERE o.minimumAttendees = ?1"
 *    description="MINIMUMATTENDEES is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByMaximumAttendees(int maximumAttendees)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM GroupPricingRule o WHERE o.maximumAttendees = ?1"
 *    description="MAXIMUMATTENDEES is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByDiscountPerAttendee(double discountPerAttendee)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM GroupPricingRule o WHERE o.discountPerAttendee = ?1"
 *    description="DISCOUNTPERATTENDEE is not indexed."
 *
 * @ejb.persistence table-name="GROUPPRICINGRULES"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class GroupPricingRuleBean implements javax.ejb.EntityBean {

   /**
    * Returns the ruleName
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the ruleName
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_RULENAME"
    */
   public abstract java.lang.String getRuleName();

   /**
    * Sets the ruleName
    *
    * @param java.lang.String the new ruleName value
    */
   public abstract void setRuleName(java.lang.String ruleName);

   /**
    * Returns the minimumAttendees
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the minimumAttendees
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="MINIMUMATTENDEES"
    */
   public abstract int getMinimumAttendees();

   /**
    * Sets the minimumAttendees
    *
    * @param int the new minimumAttendees value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setMinimumAttendees(int minimumAttendees);

   /**
    * Returns the maximumAttendees
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the maximumAttendees
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="MAXIMUMATTENDEES"
    */
   public abstract int getMaximumAttendees();

   /**
    * Sets the maximumAttendees
    *
    * @param int the new maximumAttendees value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setMaximumAttendees(int maximumAttendees);

   /**
    * Returns the discountPerAttendee
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the discountPerAttendee
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="DISCOUNTPERATTENDEE"
    */
   public abstract double getDiscountPerAttendee();

   /**
    * Sets the discountPerAttendee
    *
    * @param double the new discountPerAttendee value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setDiscountPerAttendee(double discountPerAttendee);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.String ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.
      setRuleName(com.ejdoab.tcms.entities.GroupPricingRuleUtil.generateGUID(this));

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param minimumAttendees the minimumAttendees value
    * @param maximumAttendees the maximumAttendees value
    * @param discountPerAttendee the discountPerAttendee value
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.String ejbCreate( int minimumAttendees, int maximumAttendees, double discountPerAttendee ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.
      setRuleName(com.ejdoab.tcms.entities.GroupPricingRuleUtil.generateGUID(this));

      // Set CMP fields
      setMinimumAttendees(minimumAttendees);
      setMaximumAttendees(maximumAttendees);
      setDiscountPerAttendee(discountPerAttendee);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param minimumAttendees the minimumAttendees value
    * @param maximumAttendees the maximumAttendees value
    * @param discountPerAttendee the discountPerAttendee value
    */
   public void ejbPostCreate( int minimumAttendees, int maximumAttendees, double discountPerAttendee ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-grouppricingrules-class-code.txt found.

}
