package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: PRESENTERS
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Presenter"
 *    local-jndi-name="ejb.PresenterLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Presenter o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByCompany(java.lang.String company)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Presenter o WHERE o.company = ?1"
 *    description="COMPANY is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByBio(java.lang.String bio)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Presenter o WHERE o.bio = ?1"
 *    description="BIO is not indexed."
 *
 * @ejb.persistence table-name="PRESENTERS"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class PresenterBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the company
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the company
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="COMPANY"
    */
   public abstract java.lang.String getCompany();

   /**
    * Sets the company
    *
    * @param java.lang.String the new company value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setCompany(java.lang.String company);

   /**
    * Returns the bio
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the bio
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="BIO"
    */
   public abstract java.lang.String getBio();

   /**
    * Sets the bio
    *
    * @param java.lang.String the new bio value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setBio(java.lang.String bio);

   /**
    * This is a bi-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.ConferenceAbstractLocal.
    * middlegen.plugins.entitybean.Entity20Table@1b82d69
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="PRESENTERS-cmp20-ABSTRACTS-cmp20"
    *    role-name="PRESENTERS-cmp20-has-ABSTRACTS-cmp20"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    */
   public abstract java.util.Collection getConferenceAbstracts();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.ConferenceAbstractLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.ConferenceAbstractLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param conferenceAbstracts the new CMR value
    */
   public abstract void setConferenceAbstracts(java.util.Collection conferenceAbstracts);

   /**
    * This is a bi-directional one-to-one relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.UserLocal.
    *
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="USERS-cmp20-PRESENTERS-cmp20"
    *    role-name="PRESENTERS-cmp20-has-USERS-cmp20"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_USERID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_USERID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.UserLocal getUser();

   /**
    * Sets the related com.ejdoab.tcms.entities.UserLocal
    *
    * @param com.ejdoab.tcms.entities.PresenterLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param user the new CMR value
    */
   public abstract void setUser(com.ejdoab.tcms.entities.UserLocal user);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "PRESENTERS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param company the company value
    * @param bio the bio value
    * @param user CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String company, java.lang.String bio, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "PRESENTERS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setCompany(company);
      setBio(bio);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param company the company value
    * @param bio the bio value
    * @param user CMR field
    */
   public void ejbPostCreate( java.lang.String company, java.lang.String bio, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Set CMR fields
      setUser(user);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-presenters-class-code.txt found.

}
