package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: QUESTIONNAIRES
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Questionnaire"
 *    local-jndi-name="ejb.QuestionnaireLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Questionnaire o"
 *
 * @ejb.persistence table-name="QUESTIONNAIRES"
 *
 * @weblogic.cache concurrency-strategy="ReadOnly"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class QuestionnaireBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.QuestionLocal.
    *
    *
    * @ejb.relation
    *    name="QUESTIONS-cmp20-QUESTIONNAIRES-cmp20"
    *    role-name="QUESTIONNAIRES-cmp20-has-QUESTIONS-cmp20"
    *    target-ejb="Question"
    *    target-role-name="QUESTIONS-cmp20-has-QUESTIONNAIRES-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_QUESTIONID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_QUESTIONID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.QuestionLocal getQuestion();

   /**
    * Sets the related com.ejdoab.tcms.entities.QuestionLocal
    *
    * @param com.ejdoab.tcms.entities.QuestionnaireLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param question the new CMR value
    */
   public abstract void setQuestion(com.ejdoab.tcms.entities.QuestionLocal question);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.PresentationLocal.
    *
    *
    * @ejb.relation
    *    name="PRESENTATIONS-cmp20-QUESTIONNAIRES-cmp20"
    *    role-name="QUESTIONNAIRES-cmp20-has-PRESENTATIONS-cmp20"
    *    target-ejb="Presentation"
    *    target-role-name="PRESENTATIONS-cmp20-has-QUESTIONNAIRES-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_PRESENTATIONID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_PRESENTATIONID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.PresentationLocal getPresentation();

   /**
    * Sets the related com.ejdoab.tcms.entities.PresentationLocal
    *
    * @param com.ejdoab.tcms.entities.QuestionnaireLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param presentation the new CMR value
    */
   public abstract void setPresentation(com.ejdoab.tcms.entities.PresentationLocal presentation);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.AnswerLocal.
    * middlegen.plugins.entitybean.Entity20Table@1fa490e
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="QUESTIONNAIRES-cmp20-ANSWERS-cmp20"
    *    role-name="QUESTIONNAIRES-cmp20-has-ANSWERS-cmp20"
    *    target-ejb="Answer"
    *    target-role-name="ANSWERS-cmp20-has-QUESTIONNAIRES-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_QUESTIONNAIREID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_QUESTIONNAIREID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getAnswers();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.AnswerLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.AnswerLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param answers the new CMR value
    */
   public abstract void setAnswers(java.util.Collection answers);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param question mandatory CMR field
    * @param presentation mandatory CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( com.ejdoab.tcms.entities.QuestionLocal question, com.ejdoab.tcms.entities.PresentationLocal presentation ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "QUESTIONNAIRES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param question mandatory CMR field
    * @param presentation mandatory CMR field
    */
   public void ejbPostCreate( com.ejdoab.tcms.entities.QuestionLocal question, com.ejdoab.tcms.entities.PresentationLocal presentation ) throws javax.ejb.CreateException {
      // Set CMR fields
      setQuestion(question);
      setPresentation(presentation);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-questionnaires-class-code.txt found.

}
