package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: QUESTIONS
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Question"
 *    local-jndi-name="ejb.QuestionLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Question o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByQuestionText(java.lang.String questionText)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Question o WHERE o.questionText = ?1"
 *    description="QUESTIONTEXT is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByQuestionType(int questionType)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Question o WHERE o.questionType = ?1"
 *    description="QUESTIONTYPE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByQuestionChoices(java.lang.String questionChoices)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Question o WHERE o.questionChoices = ?1"
 *    description="QUESTIONCHOICES is not indexed."
 *
 * @ejb.persistence table-name="QUESTIONS"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class QuestionBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the questionText
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the questionText
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="QUESTIONTEXT"
    */
   public abstract java.lang.String getQuestionText();

   /**
    * Sets the questionText
    *
    * @param java.lang.String the new questionText value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setQuestionText(java.lang.String questionText);

   /**
    * Returns the questionType
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the questionType
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="QUESTIONTYPE"
    */
   public abstract int getQuestionType();

   /**
    * Sets the questionType
    *
    * @param int the new questionType value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setQuestionType(int questionType);

   /**
    * Returns the questionChoices
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the questionChoices
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="QUESTIONCHOICES"
    */
   public abstract java.lang.String getQuestionChoices();

   /**
    * Sets the questionChoices
    *
    * @param java.lang.String the new questionChoices value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setQuestionChoices(java.lang.String questionChoices);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.QuestionnaireLocal.
    * middlegen.plugins.entitybean.Entity20Table@18b8914
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="QUESTIONS-cmp20-QUESTIONNAIRES-cmp20"
    *    role-name="QUESTIONS-cmp20-has-QUESTIONNAIRES-cmp20"
    *    target-ejb="Questionnaire"
    *    target-role-name="QUESTIONNAIRES-cmp20-has-QUESTIONS-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_QUESTIONID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_QUESTIONID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getQuestionnaires();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.QuestionnaireLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.QuestionnaireLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param questionnaires the new CMR value
    */
   public abstract void setQuestionnaires(java.util.Collection questionnaires);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param questionType the questionType value
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( int questionType ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "QUESTIONS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setQuestionType(questionType);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param questionType the questionType value
    */
   public void ejbPostCreate( int questionType ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param questionText the questionText value
    * @param questionType the questionType value
    * @param questionChoices the questionChoices value
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String questionText, int questionType, java.lang.String questionChoices ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "QUESTIONS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setQuestionText(questionText);
      setQuestionType(questionType);
      setQuestionChoices(questionChoices);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param questionText the questionText value
    * @param questionType the questionType value
    * @param questionChoices the questionChoices value
    */
   public void ejbPostCreate( java.lang.String questionText, int questionType, java.lang.String questionChoices ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-questions-class-code.txt found.

}
