package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: SCHEDULEENTRIES
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="ScheduleEntry"
 *    local-jndi-name="ejb.ScheduleEntryLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM ScheduleEntry o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByName(java.lang.String name)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM ScheduleEntry o WHERE o.name = ?1"
 *    description="NAME is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByDescription(java.lang.String description)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM ScheduleEntry o WHERE o.description = ?1"
 *    description="DESCRIPTION is not indexed."
 *
 * @ejb.persistence table-name="SCHEDULEENTRIES"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class ScheduleEntryBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the name
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the name
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="NAME"
    */
   public abstract java.lang.String getName();

   /**
    * Sets the name
    *
    * @param java.lang.String the new name value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setName(java.lang.String name);

   /**
    * Returns the description
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the description
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="DESCRIPTION"
    */
   public abstract java.lang.String getDescription();

   /**
    * Sets the description
    *
    * @param java.lang.String the new description value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setDescription(java.lang.String description);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.SessionLocal.
    *
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="SESSIONS-cmp20-SCHEDULEENTRIES-cmp20"
    *    role-name="SCHEDULEENTRIES-cmp20-has-SESSIONS-cmp20"
    *    target-ejb="Session"
    *    target-role-name="SESSIONS-cmp20-has-SCHEDULEENTRIES-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_SESSIONID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_SESSIONID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.SessionLocal getSession();

   /**
    * Sets the related com.ejdoab.tcms.entities.SessionLocal
    *
    * @param com.ejdoab.tcms.entities.ScheduleEntryLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param session the new CMR value
    */
   public abstract void setSession(com.ejdoab.tcms.entities.SessionLocal session);

   /**
    * This is a bi-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.UserLocal.
    *
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="USERS-cmp20-SCHEDULEENTRIES-cmp20"
    *    role-name="SCHEDULEENTRIES-cmp20-has-USERS-cmp20"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_USERID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_USERID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.UserLocal getUser();

   /**
    * Sets the related com.ejdoab.tcms.entities.UserLocal
    *
    * @param com.ejdoab.tcms.entities.ScheduleEntryLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param user the new CMR value
    */
   public abstract void setUser(com.ejdoab.tcms.entities.UserLocal user);

   /**
    * This is a bi-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.ReminderLocal.
    * middlegen.plugins.entitybean.Entity20Table@19b6225
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="SCHEDULEENTRIES-cmp20-REMINDERS-cmp20"
    *    role-name="SCHEDULEENTRIES-cmp20-has-REMINDERS-cmp20"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    */
   public abstract java.util.Collection getReminders();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.ReminderLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.ReminderLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param reminders the new CMR value
    */
   public abstract void setReminders(java.util.Collection reminders);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "SCHEDULEENTRIES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param name the name value
    * @param description the description value
    * @param session CMR field
    * @param user CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String name, java.lang.String description, com.ejdoab.tcms.entities.SessionLocal session, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "SCHEDULEENTRIES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setName(name);
      setDescription(description);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param name the name value
    * @param description the description value
    * @param session CMR field
    * @param user CMR field
    */
   public void ejbPostCreate( java.lang.String name, java.lang.String description, com.ejdoab.tcms.entities.SessionLocal session, com.ejdoab.tcms.entities.UserLocal user ) throws javax.ejb.CreateException {
      // Set CMR fields
      setSession(session);
      setUser(user);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-scheduleentries-class-code.txt found.

}
