package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: SEQ_BLOCK
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="SeqBlock"
 *    local-jndi-name="ejb.SeqBlockLocalHome"
 *    view-type="local"
 *    primkey-field="name"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM SeqBlock o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByIdx(int idx)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM SeqBlock o WHERE o.idx = ?1"
 *    description="IDX is not indexed."
 *
 * @ejb.persistence table-name="SEQ_BLOCK"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class SeqBlockBean implements javax.ejb.EntityBean {

   /**
    * Returns the name
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the name
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="NAME"
    */
   public abstract java.lang.String getName();

   /**
    * Sets the name
    *
    * @param java.lang.String the new name value
    */
   public abstract void setName(java.lang.String name);

   /**
    * Returns the idx
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the idx
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="IDX"
    */
   public abstract int getIdx();

   /**
    * Sets the idx
    *
    * @param int the new idx value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setIdx(int idx);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param idx the idx value
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.String ejbCreate( int idx ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.
      setName(com.ejdoab.tcms.entities.SeqBlockUtil.generateGUID(this));

      // Set CMP fields
      setIdx(idx);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param idx the idx value
    */
   public void ejbPostCreate( int idx ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-seq_block-class-code.txt found.

}
