package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: TRACKS
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Track"
 *    local-jndi-name="ejb.TrackLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Track o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByTitle(java.lang.String title)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Track o WHERE o.title = ?1"
 *    description="TITLE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findBySubTitle(java.lang.String subTitle)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Track o WHERE o.subTitle = ?1"
 *    description="SUBTITLE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByDescription(java.lang.String description)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Track o WHERE o.description = ?1"
 *    description="DESCRIPTION is not indexed."
 *
 * @ejb.persistence table-name="TRACKS"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class TrackBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the title
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the title
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="TITLE"
    */
   public abstract java.lang.String getTitle();

   /**
    * Sets the title
    *
    * @param java.lang.String the new title value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setTitle(java.lang.String title);

   /**
    * Returns the subTitle
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the subTitle
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="SUBTITLE"
    */
   public abstract java.lang.String getSubTitle();

   /**
    * Sets the subTitle
    *
    * @param java.lang.String the new subTitle value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setSubTitle(java.lang.String subTitle);

   /**
    * Returns the description
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the description
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="DESCRIPTION"
    */
   public abstract java.lang.String getDescription();

   /**
    * Sets the description
    *
    * @param java.lang.String the new description value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setDescription(java.lang.String description);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.ConferenceLocal.
    *
    *
    * @ejb.relation
    *    name="CONFERENCES-cmp20-TRACKS-cmp20"
    *    role-name="TRACKS-cmp20-has-CONFERENCES-cmp20"
    *    target-ejb="Conference"
    *    target-role-name="CONFERENCES-cmp20-has-TRACKS-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_CONFERENCEID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_CONFERENCEID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.ConferenceLocal getConference();

   /**
    * Sets the related com.ejdoab.tcms.entities.ConferenceLocal
    *
    * @param com.ejdoab.tcms.entities.TrackLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param conference the new CMR value
    */
   public abstract void setConference(com.ejdoab.tcms.entities.ConferenceLocal conference);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "TRACKS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param title the title value
    * @param subTitle the subTitle value
    * @param description the description value
    * @param conference CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String title, java.lang.String subTitle, java.lang.String description, com.ejdoab.tcms.entities.ConferenceLocal conference ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "TRACKS.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setTitle(title);
      setSubTitle(subTitle);
      setDescription(description);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param title the title value
    * @param subTitle the subTitle value
    * @param description the description value
    * @param conference CMR field
    */
   public void ejbPostCreate( java.lang.String title, java.lang.String subTitle, java.lang.String description, com.ejdoab.tcms.entities.ConferenceLocal conference ) throws javax.ejb.CreateException {
      // Set CMR fields
      setConference(conference);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-tracks-class-code.txt found.

}
