package com.ejdoab.tcms.entities;

/**
 * A TCMS domain entity for table: VENUES
 * Generated by Middlegen CMP2.0 Plugin 
 *
 * @author <a href="http://boss.bekk.no/boss/middlegen/">Middlegen</a>
 *
 *
 * @ejb.bean
 *    type="CMP"
 *    cmp-version="2.x"
 *    name="Venue"
 *    local-jndi-name="ejb.VenueLocalHome"
 *    view-type="local"
 *    primkey-field="id"
 *
 * @ejb.finder
 *    signature="java.util.Collection findAll()"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT OBJECT(o) FROM Venue o"
 *
 * @ejb.finder
 *    signature="java.util.Collection findByName(java.lang.String name)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Venue o WHERE o.name = ?1"
 *    description="NAME is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByPhone(java.lang.String phone)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Venue o WHERE o.phone = ?1"
 *    description="PHONE is not indexed."
 *
 * @ejb.finder
 *    signature="java.util.Collection findByFax(java.lang.String fax)"
 *    result-type-mapping="Local"
 *    method-intf="LocalHome"
 *    query="SELECT DISTINCT OBJECT(o) FROM Venue o WHERE o.fax = ?1"
 *    description="FAX is not indexed."
 *
 * @ejb.persistence table-name="VENUES"
 *
 * @weblogic.data-source-name $plugin.middlegen.middlegenTask.datasourceJNDIName
 */
public abstract class VenueBean implements javax.ejb.EntityBean {

   /**
    * Returns the id
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the id
    *
    * @ejb.pk-field
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PK_ID"
    */
   public abstract java.lang.Integer getId();

   /**
    * Sets the id
    *
    * @param java.lang.Integer the new id value
    */
   public abstract void setId(java.lang.Integer id);

   /**
    * Returns the name
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the name
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="NAME"
    */
   public abstract java.lang.String getName();

   /**
    * Sets the name
    *
    * @param java.lang.String the new name value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setName(java.lang.String name);

   /**
    * Returns the phone
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the phone
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="PHONE"
    */
   public abstract java.lang.String getPhone();

   /**
    * Sets the phone
    *
    * @param java.lang.String the new phone value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setPhone(java.lang.String phone);

   /**
    * Returns the fax
    * @todo support OracleClob,OracleBlob on WLS
    *
    * @return the fax
    *
    * @ejb.interface-method view-type="local"
    * @ejb.persistence column-name="FAX"
    */
   public abstract java.lang.String getFax();

   /**
    * Sets the fax
    *
    * @param java.lang.String the new fax value
    * @ejb.interface-method view-type="local"
    */
   public abstract void setFax(java.lang.String fax);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return the related com.ejdoab.tcms.entities.AddressLocal.
    *
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="ADDRESSES-cmp20-VENUES-cmp20"
    *    role-name="VENUES-cmp20-has-ADDRESSES-cmp20"
    *    target-ejb="Address"
    *    target-role-name="ADDRESSES-cmp20-has-VENUES-cmp20"
    *    target-multiple="yes"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.column-map
    *    foreign-key-column="FK_ADDRESSID"
    *    key-column="PK_ID"
    *
    * @jboss.relation
    *    fk-constraint="true"
    *    fk-column="FK_ADDRESSID"
    *    related-pk-field="id"
    *
    */
   public abstract com.ejdoab.tcms.entities.AddressLocal getAddress();

   /**
    * Sets the related com.ejdoab.tcms.entities.AddressLocal
    *
    * @param com.ejdoab.tcms.entities.VenueLocal the related $target.variableName
    *
    * @ejb.interface-method view-type="local"
    *
    * @param address the new CMR value
    */
   public abstract void setAddress(com.ejdoab.tcms.entities.AddressLocal address);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.ConferenceLocal.
    * middlegen.plugins.entitybean.Entity20Table@c95daa
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    *
    * @ejb.relation
    *    name="VENUES-cmp20-CONFERENCES-cmp20"
    *    role-name="VENUES-cmp20-has-CONFERENCES-cmp20"
    *    target-ejb="Conference"
    *    target-role-name="CONFERENCES-cmp20-has-VENUES-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_VENUEID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_VENUEID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getConferences();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.ConferenceLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.ConferenceLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param conferences the new CMR value
    */
   public abstract void setConferences(java.util.Collection conferences);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.BoothLocal.
    * middlegen.plugins.entitybean.Entity20Table@3c86e9
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="VENUES-cmp20-BOOTHS-cmp20"
    *    role-name="VENUES-cmp20-has-BOOTHS-cmp20"
    *    target-ejb="Booth"
    *    target-role-name="BOOTHS-cmp20-has-VENUES-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_VENUEID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_VENUEID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getBooths();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.BoothLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.BoothLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param booths the new CMR value
    */
   public abstract void setBooths(java.util.Collection booths);

   /**
    * This is a uni-directional one-to-many relationship CMR method
    *
    * @return a java.util.Collection of related com.ejdoab.tcms.entities.RoomLocal.
    * middlegen.plugins.entitybean.Entity20Table@1bd669d
    * class middlegen.plugins.entitybean.Entity20Table
    * middlegen.plugins.entitybean.Entity20Table
    * @ejb.interface-method view-type="local"
    *
    * @ejb.relation
    *    name="VENUES-cmp20-ROOMS-cmp20"
    *    role-name="VENUES-cmp20-has-ROOMS-cmp20"
    *    target-ejb="Room"
    *    target-role-name="ROOMS-cmp20-has-VENUES-cmp20"
    *    target-multiple="no"
    *
    * @jboss.relation-mapping style="foreign-key"
    *
    * @weblogic.target-column-map
    *    foreign-key-column="FK_VENUEID"
    *    key-column="PK_ID"
    *
    * @jboss.target-relation
    *    fk-constraint="true"
    *    fk-column="FK_VENUEID"
    *    related-pk-field="id"
    *
    */
   public abstract java.util.Collection getRooms();

   /**
    * Sets a collection of related com.ejdoab.tcms.entities.RoomLocal
    *
    * @param a collection of related com.ejdoab.tcms.entities.RoomLocal
    *
    * @ejb.interface-method view-type="local"
    *
    * @param rooms the new CMR value
    */
   public abstract void setRooms(java.util.Collection rooms);

   /**
    * This create method takes only mandatory (non-nullable) parameters.
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate(  ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "VENUES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    */
   public void ejbPostCreate(  ) throws javax.ejb.CreateException {
      // Set CMR fields
   }

   /**
    * This create method takes all parameters (both nullable and not nullable). 
    *
    * When the client invokes a create method, the EJB container invokes the ejbCreate method. 
    * Typically, an ejbCreate method in an entity bean performs the following tasks: 
    * <UL>
    * <LI>Inserts the entity state into the database.</LI>
    * <LI>Initializes the instance variables.</LI>
    * <LI>Returns the primary key.</LI>
    * </UL>
    *
    * @param name the name value
    * @param phone the phone value
    * @param fax the fax value
    * @param address CMR field
    * @return the primary key of the new instance
    *
    * @ejb.create-method
    */
   public java.lang.Integer ejbCreate( java.lang.String name, java.lang.String phone, java.lang.String fax, com.ejdoab.tcms.entities.AddressLocal address ) throws javax.ejb.CreateException {
      // Use Middlegen's Sequence Block PK generator. Only works for numeric fields
      try {
         com.ejdoab.tcms.entities.SequenceSessionLocal sequenceGenerator = 
         com.ejdoab.tcms.entities.SequenceSessionUtil.getLocalHome().create();      
         setId(new java.lang.Integer(sequenceGenerator.getNextSequenceNumber( "VENUES.PK_ID" )));
      } catch( javax.naming.NamingException e ) {
         throw new javax.ejb.CreateException(e.getMessage());
      }
      // Use XDoclet's GUID generator. Only works for String fields
      // This requires <utilobject includeGUID="true"/> in ejbdoclet.

      // Set CMP fields
      setName(name);
      setPhone(phone);
      setFax(fax);
      // EJB 2.0 spec says return null for CMP ejbCreate methods.
      return null;
   }

   /**
    * The container invokes thos method immediately after it calls ejbCreate. 
    *
    * @param name the name value
    * @param phone the phone value
    * @param fax the fax value
    * @param address CMR field
    */
   public void ejbPostCreate( java.lang.String name, java.lang.String phone, java.lang.String fax, com.ejdoab.tcms.entities.AddressLocal address ) throws javax.ejb.CreateException {
      // Set CMR fields
      setAddress(address);
   }

     
   // No C:\tcms\src\middlegen\merge/cmp20-venues-class-code.txt found.

}
