DROP TABLE Answers;
DROP TABLE Questionnaires
DROP TABLE Questions;
DROP TABLE GroupPricingRules;
DROP TABLE RegistrationDatePricingRules;
DROP TABLE Reminders;
DROP TABLE UserRoles;
DROP TABLE Roles;
DROP TABLE ScheduleEntries; 
DROP TABLE Sessions;
DROP TABLE Presentations;
DROP TABLE PresentationTopics;
DROP TABLE PresentationLevels;
DROP TABLE PresentationTypes;
DROP TABLE Attendees;
DROP TABLE Abstracts;
DROP TABLE Presenters;
DROP TABLE Users;
DROP TABLE AbstractStatus;
DROP TABLE Booths;
DROP TABLE Rooms;
DROP TABLE Tracks;
DROP TABLE Conferences;
DROP TABLE Venues;
DROP TABLE Addresses;
DROP TABLE News;

-- Middlegen Sequence Block Pattern Table
-- Never drop an autogenerated table just clean it
DELETE FROM SEQ_BLOCK;